# -*- coding: utf-8 -*-
"""drawOperatorsRectangle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qsysnoV7f-rBQV1AZcx3oCCpU31uErV5
"""



print("+" + 10 * "-" + "+")
print(("|" + " " * 10 + "|\n") * 5)
print("+" + 10 * "-" + "+")

"""## **Output**:Rectangle"""

print("+" + 10 * "-" + "+")
print(("|" + " " * 10 + "|\n") * 7,end="")
print("+" + 10 * "-" + "+")

print("+" + 10 * "-" + "+")
print(("|" + " " * 10 + "|\n") * 5,end=" ")
print("+" + 10 * "-" + "+")