# -*- coding: utf-8 -*-
"""Multi-line printing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pr9n5pk0ROYkj056fnFQ7P7m-OsosUgX

# Multi-line printing

Use triple quotes to print strings on multiple lines in order to make text easier to read, or create a special text-based design.
"""

secret_number = 777

print(
"""
+================================+
| Welcome to my game, muggle!    |
| Enter an integer number        |
| and guess what number I've     |
| picked for you.                |
| So, what is the secret number? |
+================================+
""")