# -*- coding: utf-8 -*-
"""PowersOfTwo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XL5IT6wW2fuCV16-poqRByPnazCCptpF

```
 write some of the first powers of two
```
"""

power = 1
for expo in range(16):
    print("2 to the power of", expo, "is", power)
    power *= 2