# -*- coding: utf-8 -*-
"""Python_Variables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sM1SJ-i0J9NKdYWdizW4qJLdMbgo-lbE
"""

print("My\nname\nis\nBond.", end=" ")
print("James Bond.")

print(sep="&", "fish", "chips")

print( "fish", sep="&","chips")

print( "fish", "chips",sep=" &")

print('Greg\"s\" book.')
print('"Greg\'s\' book."')
print("'Greg\'s book.'")
"""


print("Greg\'s book.")
print('"Greg's book."')
"""

print((2 ** 4), (2 * 4.), (2 * 4))

print((-2 / 4), (2 / 4), (2 // 4), (-2 // 4))

print((2 % -4), (2 % 4), (2 ** 3 ** 2))

var = 2
var = 3
print(var)

x = 5
y = 10
z = 8

print(x > y)
print(y > z)

